spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: f8150ec1e6fbcdca55db
            clientSecret: a26255f77c013541fa72d7cae8e67e77a2b0cf62
server:
  port: 9090